[package]
name = "nomad_sim"
version = "0.1.2"
edition = "2021"
readme = "README.md"
repository = "https://github.com/msanlli/nomad_sim.git"
license = "MIT"

[dependencies]
device_query = "2.0.0"
clearscreen = "2.0.1"
csv = "1.3.0"